apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
    containers:
      - name: web
        image: web
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:h2:tcp://database-service:9092/./jpadb  # URL do banco de dados H2 no serviço de banco de dados
        imagePullPolicy: Never