version: '3.8'

services:

  h2database:
    build:
      context: .
      dockerfile: DockerfileDb
    container_name: h2database
    ports:
      - "8082:8082"
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -ifNotExists  # Configure H2 database options to allow TCP connections

  web-app:
    build:
      context: .
      dockerfile: DockerfileWeb
    container_name: web-application
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2database:9092/./jpadb
    depends_on:
      - h2database