apiVersion: v1
kind: Deployment
metadata:
  name: database-server
  labels:
    app:
spec:
  replicas: 2
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
  spec:
    containers:
      - name: database
        image: db
        ports:
          - containerPort: 8082
