apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app:
spec:
  replicas: 1
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name: web
        image: web
        ports:
          - containerPort: 8080